<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="bugfixes.xsl"?>

<!-- The following bugs have been fixed since the omniORBpy 1.0     -->
<!-- release. This file is transformed into html with bugfixes.xsl. -->

<!-- Editors: make sure the content you add is well-formed XML.     -->

<buglist version="1.2">

<bug id="7" date="Thu Sep 21 14:14:30 BST 2000" user="dpg1">

  <summary>Assertion failure mashalling sequence of any</summary>
  <reported>Carsten Seibert</reported>
  <link href="http://www.uk.research.att.com/omniORB/archives/2000-09/0109.html"/>
</bug>

<bug id="6" date="Thu Sep 21 11:53:11 BST 2000" user="dpg1">

  <summary>Race condition in C++ servant deletion</summary>
  <reported>Gary Pennington</reported>
  <link	href="http://www.uk.research.att.com/omniORB/archives/2000-09/0063.html"/>
  <text>
  A race condition in reference counting meant that a thread would
  occasionally attempt to use a C++ servant object while another
  thread was in the process of deleting it.
  </text>
</bug>

<bug id="5" date="Wed Sep  6 12:13:30 BST 2000" user="dpg1">

  <summary>Support for Python 1.6 and 2.0b1</summary>
  <text>
  omniORBpy was hard-coded to require Python 1.5.2, just in case later
  versions were incompatible. 1.6 and 2.0b1 are compatible, so they
  are now supported.
  </text>
</bug>

<bug id="4" date="Fri Sep  1 15:07:45 BST 2000" user="dpg1">

  <summary>Memory leak when returning invalid data</summary>
  <text>
  If the data returned from a CORBA call was invalid, causing a
  BAD_PARAM (or other) exception, the invalid data would be leaked.
  </text>
</bug>

<bug id="3" date="Wed Aug 23 10:15:43 BST 2000" user="dpg1">

  <summary>Interface Repository stubs not available with "import
  CORBA"</summary>
  <reported>Richard Gruet</reported>
  <text>
  The <code>OMNIORBPY_IMPORT_IR_STUBS</code> environment variable
  worked with "<code>from omniORB import CORBA</code>", but not
  "<code>import CORBA</code>".
  </text>
</bug>

<bug id="2" date="Tue Aug 22 17:01:50 BST 2000" user="dpg1">

  <summary>Instability after unexpected user exceptions</summary>
  <text>
  After the fix on 17 August (see the update.log), when an unexpected
  user exception was raised in an up-call, the Python error status
  would not be properly cleared. This meant that later up-calls could
  fail with exceptions of the form "AttributeError: minor", even when
  the code didn't mention "minor" at all.
  </text>

</bug>


<bug id="1" date="Tue Aug 22 12:44:57 BST 2000" user="dpg1">

  <summary>omniidl back-end generates useless classes for typedef to
  struct/union</summary>

  <reported>Jimmy Wilson</reported>
  <link href="http://www.uk.research.att.com/omniORB/archives/2000-08/0172.html"/>
  <text>
  The Python mapping specification is totally silent on the issue of
  typedefs. The only thing it says is that <em>something</em> must be
  generated for all declared types, to be passed to
  <code>CORBA.id()</code>. It does make sense to allow typedef names
  to be used to contruct structs and unions, though.
  </text>
</bug>

</buglist>
